Story 6 issue fixes
GigiLoria5/se2022-08-HireTracker pull request #67
Opened 2022-12-05 17:06 UTC by ciaccogiuseppe

2022-12-06 13:56 UTC, GigiLoria5 commented
Does it solve #49 ?

2022-12-06 18:12 UTC, ciaccogiuseppe commented
yes, it solves issue #49

2022-12-07 20:27 UTC, GigiLoria5 requested changes
There are still problems:
- in the db the capacity of existing car parks is null
- there are conflicts preventing merge

If this branch also contains the FE changes, then ...
- there is still the problem that latitude and longitude are on the same line
- the map is still too low in height
- the fields should be grouped with subtitles as done in the other pages... (GPS COORDINATES, GEOGRAPHIC INFORMATION and maybe PARKING LOT INFORMATION)
- point consistency check does not work (I added a car park with point in turin and country saudi arabia)

2022-12-09 15:02 UTC, GigiLoria5 approved these changes

2022-12-09 16:12 UTC, merged